services:
  client:
    image: 
    container_name: client
    ports:
      - "3000:80"
    networks:
      - app-network

  server:
    image: 
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - CONNECTION_URL= module://mongo:27017
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
